GET http://127.0.0.1:8000/driver-register
Content-Type: application/json

{
    "driverPassword" : "wwwwww",
    "driverConfirmPassword" : "wwwwww",
    "driverName" : "RobertSoCool",
    "driverMobile" : "7878787878",
    "driverPicture" : "[ FILE ]",
    "driverEmail" : "robert@cool.com",
    "driverNRIC" : "58568468",
    "driverVehicleType" : "Bike (Weight < 8KG)",
    "driverVehicleNumber" : "MH5C848"
}

####
GET http://127.0.0.1:8000/driver-login
Content-Type: application/json

{
    "driverMobile" : "7878787878",
    "driverPassword" : "wwwwww"
}

####
GET http://127.0.0.1:8000/driver-details
Content-Type: application/json
Auth: 159e8adde2d2242bb5b9fd47926fcf0e

{
    "driverId" : "50"
}

####
GET http://127.0.0.1:8000/driver-available-jobs
Content-Type: application/json
Auth: 59dd4219db56728d500b9e83f40cdf34

{
    "driverId" : "7"
}

####
GET http://127.0.0.1:8000/driver-active-jobs
Content-Type: application/json
Auth: 59dd4219db56728d500b9e83f40cdf34


{
    "driverId" : "7"
}

####
GET http://127.0.0.1:8000/driver-history-jobs
Content-Type: application/json

{
    "driverId" : "3"
}

####
GET http://127.0.0.1:8000/driver-job-details
Content-Type: application/json

{
    "driverId" : "3"
}

####
GET http://127.0.0.1:8000/customer-register
Content-Type: application/json

{
    "customerMobile" : "9876543210",
    "customerPassword" : "Password",
    "customerConfirmPassword": "Password",
    "customerName" : "Name Name",
    "customerEmail" : "mail@mail.com"
}

####
GET http://127.0.0.1:8000/customer-login
Content-Type: application/json

{
    "customerMobile" : "9876543210",
    "customerPassword" : "Password"
}

####
GET http://127.0.0.1:8000/customer-details
Content-Type: application/json

{
    "customerMobile" : "9876543210",
    "customerPassword" : "Password"
}


#####
GET http://127.0.0.1:8000/customer-create-job
Content-Type: application/json

{
    "customerName" : "Melisa Tan",
    "customerMobile" : "989496843",
    "deliveryTime" : "31 Aug 12:20PM",
    "dropOffLocation" : "Toa Poyah",
    "dropUnitNumber" : "04-123",
    "pickupLocation" : "Potang Pasir",
    "pickupUnitNumber" : "04-123",
    "requiredVehicle" : "Bike, (Weight < 8kg)",
    "priceOfDelivery" : "400",
    "scheduleDelivery" : false,
    "scheduleDate" : "Today (29th Aug)",
    "scheduleTime" : "11:10 AM",
    "driverNotes" : "TextField",
    "paymentMode" : "Wallet",
    "paymentId" : "id"
}


#####
GET http://127.0.0.1:8000/customer-wallet-topup
Content-Type: application/json

{
    "customerId" : "asdasf",
    "topupAmount" : "864658768",
    "cardName" : "Toa Poyah",
    "cardNumber" : "76543456789",
    "cardExpiry" : "MM/YY",
    "cardCvv" : 765
}

#####
GET http://127.0.0.1:8000/customer-wallet-withdraw
Content-Type: application/json

{
    "customerId" : "asdasf",
    "withdrawAmount" : "864658768",
    "cardName" : "Toa Poyah",
    "cardNumber" : "76543456789",
    "cardExpiry" : "MM/YY",
    "cardCvv" : 765
}


#####
GET http://127.0.0.1:8000/customer-transaction-list
Content-Type: application/json

{
    "customerId" : "458uiubdvu63gdbi7"
}

#####
GET http://127.0.0.1:8000/customer-jobs
Content-Type: application/json

{
    "customerId" : 1234567
}

#####
GET http://127.0.0.1:8000/company-register
Content-Type: application/json

{
    "companyUEN" : "ytrertyu",
    "companyAcra" : "[FILE]",
    "companyPassword" : "Password",
    "companyName" : "RobertSoCool",
    "companyEmail" : "robert@cool.com"
}

#####
GET http://127.0.0.1:8000/company-login 
Content-Type: application/json

{
    "companyMobile" : "864658768",
    "companyPassword" : "Password"
}


#####
GET http://127.0.0.1:8000/company-detail
Content-Type: application/json

{
    "companyId" : "1234567"
}


#####
GET http://127.0.0.1:8000/company-driver-register
Content-Type: application/json

{
    "companyId" : "hrdsdftyuijhgf",
    "driverMobile" : "864658768",
    "driverPassword" : "Password",
    "driverName" : "RobertSoCool",
    "driverMobile" : "989496843",
    "driverPicture" : "FILE",
    "driverEmail" : "robert@cool.com",
    "driverNRIC" : "58568468",
    "driverVehicleType" : "Bike (Weight < 8KG)",
    "driverVehicleNumber" : "MH5C848"
}

#####
GET http://127.0.0.1:8000/company-drivers
Content-Type: application/json

{
    "companyId" : "hrdsdftyuijhgf"
}

#####
GET http://127.0.0.1:8000/company-jobs
Content-Type: application/json

{
    "companyId" : 1234567,
    "Drivers" : 987654    
}


#####
GET http://127.0.0.1:8000/company-job-detail
Content-Type: application/json

{
    "jobId": 8765,
    "companyId": 6567
}


#####
GET http://127.0.0.1:8000/allocate-driver
Content-Type: application/json

{
    "jobId" : 8765,
    "driverId" : 6567
}




#####
GET http://127.0.0.1:8000/admin-login
Content-Type: application/json

{
    "adminMobile" : "864658768",
    "adminPassword" : "Password"
}


#####
GET http://127.0.0.1:8000/admin-all-jobs
Content-Type: application/json

{
    "adminId" : "hrdsdftyuijhgf"
}

#####
GET http://127.0.0.1:8000/admin-whole-drivers
Content-Type: application/json

{
    "adminId" : "hrdsdftyuijhgf"
}

#####
GET http://127.0.0.1:8000/admin-whole-company
Content-Type: application/json

{
   "adminId" : "hrdsdftyuijhgf"
}
#####
GET http://127.0.0.1:8000/admin-whole-customer
Content-Type: application/json

{
    "adminId" : "hrdsdftyuijhgf"
}