######
GET https://localhost:8000/customer-login
Content-Type: application/json

{
    "customerMobile" : "9876543210",
    "password" : "New Password" 
}

######
GET https://localhost:8000/customer-register
Content-Type: application/json

{
    "customerName" : "New Name",
    "customerEmail" : "mail@mail.com",
    "customerMobile" : "9876543210",
    "password" : "New Password"
}

######
GET https://localhost:8000/customer-forgot-password
Content-Type: application/json

{
    "customerPhone" : "9876543210"
}


######
GET https://localhost:8000/customer-forgot-password
Content-Type: application/json
Auth: {Token} 

{
    "customerEmail" : "mail@mail.com"
}


######
GET https://localhost:8000/customer-place-order
Content-Type: application/json
Auth: {Token} 

{
    "pickupLocation" : "mail@mail.com",
    "pickupUnitNumber" : "sdgfhjkl",
    "dropOffLocation" : "setdfhtgjkhl",
    "dropOffUnitNumber" : "asdfghjk",
    "customerName" : "sdfghjk rdghfgj",
    "customerMobile" : "886754564323",
    "priceOfDelivery" : "dsfg dfgh trjhk"
}

######
GET https://localhost:8000/place-order
Content-Type: application/json
Auth: {Token} 

{
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
}