######
GET http://localhost:3000/driver-login
Content-Type: application/json

{
    "Mobile" : "9876543210",
    "password" : "New Password" 
}

# Resposnse: 
# {
#     "driverId" : "gsahdkjl",
#     "driverMobile" : "678908765",
#     "driverName" : "hgjk hjk",
#     "driverEmail" : "mail@mail.com",
#     "token" : "fgjhklldshjkhgfdgfhjkl"
# }

######
GET http://localhost:3000/driver-register
Content-Type: application/json

{
    "driverName" : "New Name",
    "driverEmail" : "mail@mail.com",
    "password" : "New Password",
    "NRIC" : "base64 data",
    "vehicleType" : "FOur wheeler",
    "vehicleNumber" : "UP65 XXXX XXXX",
    "driverMobile" : "9876543210",
    "picture" : "base64 string"
}

# Resposnse: 
# {
#     "driverId" : "gsahdkjl",
#     "driverMobile" : "678908765",
#     "driverName" : "hgjk hjk",
#     "driverEmail" : "mail@mail.com"
# }

######
GET http://localhost:3000/driver-forgot-password
Content-Type: application/json

{
    "driverPhone" : "9876543210"
}

# Resposnse: 
# {
#   "linkToForgotPassword" : "gdshkj.com/saduifh?forgotPassword=\"cfghjkl\""
#    "mail" : "mail@mail.com"
# }


######
GET http://localhost:3000/driver-forgot-password
Content-Type: application/json

{
    "driverEmail" : "mail@mail.com"
}

# Resposnse: 
# {
#   "linkToForgotPassword" : "gdshkj.com/saduifh?forgotPassword=\"cfghjkl\""
#    "phone" : "9876543210"
# }

######
GET http://localhost:3000/driver-details
Content-Type: application/json
Auth: {Token} 


{
    "driverId" : "Generated Id"
}


# Response : 
# {
#     "driverName" : "hgjkl gyhukj",
#     "driverMobile" : "9876543210",
#     "driverEmail" : "mail@mail.com"
# }

######
GET http://localhost:3000/driver-job-details
Content-Type: application/json
Auth: {Token} 

{
    "driverId" : "Generated Id",
    "jobId" : "Generated Job Id"
}

# Response :
# {
#     "pickupLocation" : "hgjhkl hfgj",
#     "pickupUnitNumber" : "ghjk",
#     "dropOffLocation" : "gfhjkl fhgyjk",
#     "dropOffUnitNumber" : "345678654378",
#     "customerName" : "ghjk ghjk",
#     "customerMobile" : "9876543210",
#     "priceOfDelivery" : "78.00"
# }


######
GET http://localhost:3000/driver-history-jobs
Content-Type: application/json
Auth: {Token} 

{
    "driverId" : "Generated Id"
}

# Response : 
# {
#     "requiredVehicle" : "dgfhjkl;",
#     "dropOffLocation" : "gfhjkl",
#     "pickupLocation" : "dgfhjkl",
#     "orderId" : "4567890654",
#     "customerName" : "dfjkl",
#     "deliveryTime" : "8:00 pm"
# }

######
GET http://localhost:3000/driver-active-jobs
Content-Type: application/json
Auth: {Token} 

{
    "driverId" : "Generated Id"
}

# Response : 
# {
#     "requiredVehicle" : "gfhjkl",
#     "dropOffLocation" : "gfhjkl",
#     "pickupLocation" : "gfhjkl'.",
#     "orderId" : "dftgyjkuhlij;k",
#     "customerName" : "ghj fghjk",
#     "deliveryTime" : "9:00pm"
# }

######
GET http://localhost:3000/driver-available-jobs
Content-Type: application/json

{
    "driverId" : "Generated Id",
    "dropOffLocation" : "New Location"
}

# Response : 
# {
#     "requiredVehicle" : "fdghjk",
#     "orderId" : "57689",
#     "pickupLocation" : "ghjkl",
#     "dropOffLocation" : "fjgkhjkl",
#     "customerName" : "ghjkl hgjkl",
#     "priceOfDelivery" : "ghjkl",
#     "deliveryTime" : "9:00pm"
# }